### PR TITLE
biicode support

### PR DESCRIPTION
**Pull request by drodri**
Hi lectem,

As I tried things out to be able to check your stackoverflow question, I ended with this working configuration, so here it is for your convenience, in case you want to directly merge it.
Hope it clarifies things, I am also currently helping to re-write the docs so these kind of things become clearer.

Best

### CODE REVIEW

**Comment by Lectem** [comment]
Hi, 
Thanks but sadly I saw the PR after implementing the changes.
Could you explain why the example/3dsraw.c and example/3dsraw_right.c were added to the library by the way ?
I managed to remove it through the .conf file but I'm not sure if it's the right way to do things.

Thanks again !

Edit : It seems that 

```
[dependencies]
    *.c - example/*
    example/example.c + example/3dsraw.c example/3dsraw_right.c
```

didn't work

**Comment by drodri** [comment]
It is not necessary to add nothing to the dependencies section, it works as is. You can check with "bii deps" that this dependency is automatically detected thanks to the variables "imageBytes_left".

So the dependencies are correct. What is not optimal is the assignment of those sources to the lib, when you actually want just to be included in the executble example. There is no way for biicode to guess these things, it just know that example depends on those 3ds*\* files, and thinks that that would be part of the library, so what can be done is assign sources in the CMakeLists.txt. I have updated the PR, with it:

```
LIST(REMOVE_ITEM BII_LIB_SRC example/3dsraw.c
                               example/3dsraw_right.c)
SET(BII_example_example_SRC ${BII_example_example_SRC}
                               example/3dsraw.c
                               example/3dsraw_right.c)
```

This modification can be easily automated if you consider your example an automatic test. Then you could just add to your biicode.conf:

```
[tests]
     examples/*
```

And when you want to build and run it, just type:

```
$ bii test
```

I have tested the publication & reuse and it worked ok!
This is the published block: http://www.biicode.com/diego/libmpo
The test how to reuse is in: http://www.biicode.com/diego/libmporeuse
Just add a main, the 3ds files and add to biicode.conf:

```
[requirements]
    diego/libmpo: 0
[includes]
    libmpo/*: diego/libmpo/include
```

It also seems that the dependency to the jpeg9 version recently updated also works fine.
All of this is just cause I wanted to help to clarify things, I will remove them when your code is up.

**Comment by Lectem** [comment]
Thanks a lot for the help, and I'm pretty sure those pieces of information would help many people.
I went ahead with the tests solution for the examples, it is indeed more logical to build those only when asked by the user.

**Comment by drodri** [comment]
I have just checked your published version to biicode, dont know if updated yet, but I have a couple of questions:
- Why do you maintain the [dependencies] and [mains] sections? They should not be required, mains are already correctly auto detected and the same for dependencies.
- The CMakeLists.txt seems not to be updated. 
  Probably you had some problem while publishing after merging my PR?

You are totally right about this info, we are currently doing a big effort in updating the docs.
Please tell me if you have any other question.

**Comment by Lectem** [comment]
I guess you simply checked right before I published the new version on biicode !
It seems to be up to date from what I see at http://www.biicode.com/Lectem/Lectem/libmpo/master/0/biicode.conf

**Comment by drodri** [comment]
Yes, seems I did. Looks good now :)

**Pull request merged**
